# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from ..schemas._internal import Base_3, BusinessSchema_3, PlatformSchema_3


class SigningKey(BaseModel):
    """
    Public key for signature verification in JWK format.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    kid: str
    """
    Key ID. Referenced in signature headers to identify which key to use for verification.
    """
    kty: str
    """
    Key type (e.g., 'EC', 'RSA').
    """
    crv: str | None = None
    """
    Curve name for EC keys (e.g., 'P-256').
    """
    x: str | None = None
    """
    X coordinate for EC public keys (base64url encoded).
    """
    y: str | None = None
    """
    Y coordinate for EC public keys (base64url encoded).
    """
    n: str | None = None
    """
    Modulus for RSA public keys (base64url encoded).
    """
    e: str | None = None
    """
    Exponent for RSA public keys (base64url encoded).
    """
    use: Literal["sig", "enc"] | None = None
    """
    Key usage. Should be 'sig' for signing keys.
    """
    alg: str | None = None
    """
    Algorithm (e.g., 'ES256', 'RS256').
    """


class Base(BaseModel):
    """
    Base discovery profile with shared properties for all profile types.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: Base_3
    signing_keys: list[SigningKey] | None = None
    """
    Public keys for signature verification (JWK format). Used to verify signed responses, webhooks, and other authenticated messages from this party.
    """


class PlatformProfile(Base):
    """
    Full discovery profile for platforms. Exposes complete service, capability, and payment handler registries.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: PlatformSchema_3 | None = None


class BusinessProfile(Base):
    """
    Discovery profile for businesses/merchants. Subset of platform profile with business-specific configuration.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: BusinessSchema_3 | None = None


class UcpDiscoveryProfile(RootModel[PlatformProfile | BusinessProfile]):
    root: PlatformProfile | BusinessProfile = Field(
        ..., title="UCP Discovery Profile"
    )
    """
    Schema for UCP discovery profiles. Business profiles are hosted at /.well-known/ucp; platform profiles are hosted at URIs advertised in request headers.
    """
