# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from ._internal import Base_2 as Base
from ._internal import (
    BusinessSchema2,
    BusinessSchema4,
    BusinessSchema5,
    BusinessSchema6,
    BusinessSchema7,
    BusinessSchema8,
    BusinessSchema9,
    BusinessSchema10,
    BusinessSchema11,
    PlatformSchema3,
    PlatformSchema5,
    PlatformSchema6,
    PlatformSchema7,
    PlatformSchema8,
    PlatformSchema9,
    PlatformSchema10,
    PlatformSchema11,
    PlatformSchema12,
    ResponseSchema2,
    ResponseSchema4,
    ResponseSchema5,
    ResponseSchema6,
    ResponseSchema7,
    ResponseSchema8,
    ResponseSchema9,
    ResponseSchema10,
    ResponseSchema11,
    UcpService,
)
from ._internal import BusinessSchema_2 as BusinessSchema
from ._internal import PlatformSchema_2 as PlatformSchema
from ._internal import ResponseSchema_2 as ResponseSchema

__all__ = [
    "Base",
    "BusinessSchema",
    "BusinessSchema10",
    "BusinessSchema11",
    "BusinessSchema2",
    "BusinessSchema4",
    "BusinessSchema5",
    "BusinessSchema6",
    "BusinessSchema7",
    "BusinessSchema8",
    "BusinessSchema9",
    "PlatformSchema",
    "PlatformSchema10",
    "PlatformSchema11",
    "PlatformSchema12",
    "PlatformSchema3",
    "PlatformSchema5",
    "PlatformSchema6",
    "PlatformSchema7",
    "PlatformSchema8",
    "PlatformSchema9",
    "ResponseSchema",
    "ResponseSchema10",
    "ResponseSchema11",
    "ResponseSchema2",
    "ResponseSchema4",
    "ResponseSchema5",
    "ResponseSchema6",
    "ResponseSchema7",
    "ResponseSchema8",
    "ResponseSchema9",
    "UcpService",
]
